name: Monitor bot PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '18 6 * * *'

permissions:
  contents: read

jobs:
  monitor-pr:
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    uses: go-openapi/ci-workflows/.github/workflows/monitor-bot-pr.yml@fc72d680b90bf5f66c37daa95545c20ae56ac17a # v0.3.3
    secrets: inherit
